<?php

/**
 * tData - Theamus database access class
 * PHP Version 5.5.3
 * Version 1.2
 * @package Theamus
 * @link http://www.theamus.com/
 * @author Matthew Tempinski (Eyraahh) <matt.tempinski@theamus.com>
 * @copyright 2014 Matthew Tempinski
 */

class tData {
    /**
     * Contains the information given by the configuration file
     *
     * @var array $config
     */
    private $config;


    /**
     * The mysqli object for the class
     *
     * @var object $connection
     */
    private $connection;


    /**
     * The prefix to the system specific database tables
     *
     * @var string $prefix
     */
    public $prefix;


    /**
     * Holds the value of whether or not the api call failed.
     *
     * @var boolean $api_fail
     */
    private $api_fail = false;


    /**
     * Holds the value of whether or not the PDO library is being used
     *
     * @var boolean $pdo
     */
    public $use_pdo = false;


    /**
     * Debugging tool to help see the query that is generated by any of the Theamus CRUD functions
     *
     * @var boolean $show_query
     */
    public $show_query = false;


    /**
     * Debugging tool to help see errors that occured during a query
     *
     * @var boolean $show_query_errors
     */
    public $show_query_errors = false;


    /**
     * Initializes the class, defines the configuration given by the system
     *
     * @return boolean
     */
    public function __construct() {
        $this->config = $this->define_system_configuration();
        $this->set_timezone();
        return true;
    }


    /**
     * Defines the system configuration file into an array
     *
     * @return array $ret
     */
    private function define_system_configuration() {
        $config_path = path(ROOT."/config.php");
        $ret = array();
        if (file_exists($config_path)) {
            include $config_path;
            $ret = $config;
        }
        return $ret;
    }


    /**
     * Sets the timezone for the entire system
     *
     * @return
     */
    private function set_timezone() {
        $tz = isset($this->config['timezone']) ? $this->config['timezone'] : "America/Chicago";
        date_default_timezone_set($tz);
        return;
    }


    /**
     * Gets the salt value from the sytem's configuration file
     *
     * @param string $type
     * @return string
     */
    public function get_config_salt($type) {
        $salt = $this->config['salt'][$type];
        return $salt;
    }


    /**
     * Connects the system to the database, you know, to do database things
     *
     * @return boolean
     */
    public function connect($pdo = false) {
        // Check the configuration settings
        if (!isset($this->config['Database'])) {
            return false;
        }

        if ($pdo == false) {
            $connection = @new mysqli($this->config['Database']['Host Address'],
                                      $this->config['Database']['Username'],
                                      $this->config['Database']['Password'],
                                      $this->config['Database']['Name']);

            if ($connection->connect_errno) return false;
            else {
                $this->connection = $connection;
                return $connection;
            }
            return false;
        } else {
            try {
                $connection = new PDO("mysql:host=".$this->config['Database']['Host Address'].";dbname=".$this->config['Database']['Name'].";",
                    $this->config['Database']['Username'], $this->config['Database']['Password']);
                $this->connection = $connection;
                $this->use_pdo = true;
                return $connection;
            } catch (PDOException $ex) {
                return false;
            }
        }
    }


    /**
     * Disconnects from the database
     *
     * @return boolean
     */
    public function disconnect() {
        if ($this->connection) {
            if ($this->use_pdo == false) {
                $this->connection->close();
            } else {
                $this->connection = null;
            }
        }
        return false;
    }


    /**
     * Gets the system's database prefixes
     *
     * e.g. "tm"
     *
     * @return boolean
     */
    public function get_system_prefix() {
        if ($this->connection) {
            $q = $this->custom_query("SHOW TABLES");

            if ($q) {
                $rows = $this->fetch_rows($q, "fetch_array", PDO::FETCH_COLUMN);
                foreach ($rows as $row) {
                    $table = is_array($row) ? $row[0] : $row;
                    $explode = explode("_", $table);

                    if (count($explode) > 1) {
                        if ($explode[1] == "settings") return $explode[0];
                    } else {
                        continue;
                    }
                }
            }
        }
        return false;
    }


    /**
     * Takes a multi-demensional array and converts it into a single array
     *
     * @param array $array
     * @return array $ret
     */
    public function flatten_array($array) {
        if (!is_array($array)) return array($array);
        $ret = array();
        foreach ($array as $value) $ret = array_merge($ret, $this->flatten_array($value));
        return $ret;
    }


    /**
     * Decodes a Theamus specific encoding.
     * {t:<key>="<val>":} -> array("<key>"=>"<val>")s
     *
     * @param string $inp
     * @return array $ret
     * @throws Exception
     */
    public function t_decode($inp) {
        if ($inp == "") return array();

        preg_match_all('/{t:/i', $inp, $r);
        if (count($r[0]) > 1) throw new Exception("tData: Recusive encoding is not allowed.");

        preg_match("/{t:(.*?):}/i", $inp, $m);
        $exp = explode(";", $m[1]);
        foreach ($exp as $e) {
            if (strpos($e, "=") === false) $ret[] = $e;
            else {
                $iexp = explode("=", $e);
                $ret[$iexp[0]] = trim($iexp[1], "\"");
            }
        }

        return $ret;
    }


    /**
     * Takes a string of XML and converts it to an array
     *
     * @param string $xml
     * @param boolean $object
     * @return array
     */
    public function xml_decode($xml) {
        $xml_array = array(); // Define the xml results array

        // Get the contents of the XML and turn them into an array
        $xml_parser = xml_parser_create();
        xml_parse_into_struct($xml_parser, $xml, $xml_array);

        // Remove the top layer elements
        $array = array_shift($xml_array);
        unset($array["level"], $array["type"]);

        // Loop through all of the xml nodes
        for($i = 0; $i < sizeof($xml_array); $i++) {
            // Define shortcuts
            $xml_object = $xml_array[$i];
            $level      = $xml_object['level'] - 2;

            // Define the result array index
            $array_index = array();
            for ($ai = 0; $ai < $level; $ai++) {
                $array_index[] = strtolower($xml_array[$ai]['tag']);
            }
            $array_index[] = strtolower($xml_object['tag']);

            // Define the value for the current object
            if ($xml_object["type"] == "complete") {
                // Define the value of the current object
                $value = &$array;
                foreach($array_index as $segment) {
                    $value = &$value[$segment];
                }
                $value = $xml_object;

                // Don't include the xml structure items
                unset($value["level"], $value["type"], $value['tag']);
            }
        }

        // Return the array with the XML results
        return $array;
    }


    /**
     * Check to see if an array is sequential (0, 1, 2, ...) or associative ("key"=>"value")
     *
     * @param array $array
     * @return boolean
     */
    public function array_is_associative($array = array()) {
        if (empty($array)) return true;
        return array_keys($array) !== range(0, count($array) - 1);
    }


    /**
     * Check to see if a string is just encoded JSON
     *
     * @param string $string
     * @return boolean
     */
    public function string_is_json($string = "") {
        if ($string == "") return false;
        $json = json_decode($string);
        return $json == null ? false : true;
    }


    /**
     * Defines the hash that makes up the API keys or the 420hash
     *
     * @param boolean $user
     * @return string
     */
    public function get_hash($user = false) {
        // Define the hash variables
        $user_ip = $_SERVER['REMOTE_ADDR'];
        $date = $user == true ? date("Y-d-m") : "";
        $server_ip = $_SERVER['SERVER_ADDR'];

        // Return the hash
        return md5($user_ip.$date.$server_ip);
    }


    /**
     * Structures an API error to be consistent with the same error you would get from
     *  a JS API call
     *
     * @param string $message
     * @return string $return
     */
    private function api_error($message = "", $status = 200) {
        $return = array();

        // Define the error
        $return['error']['status'] = 1;
        $return['error']['message'] = $message;

        // Define the response
        $return['response']['status'] = $status;
        $return['response']['headers'] = "";
        $return['response']['data'] = "";

        return $return;
    }


    /**
     * Checks the arguments given via the API call for requirements and validation
     *
     * @param array $args
     * @return array $return
     */
    private function api_check_args($args) {
        $return = array();

        // Define defaults
        $return['ajax'] = "api";
        $return['api-from'] = "php";

        // Define the custom variable
        if (isset($args['custom'])) {
            $return['custom'] = $args['custom'] == true ? true : false;
        } else {
            $return['custom'] = false;
        }

        // Define the type
        if (isset($args['type']) && gettype($args['type']) == "string") {
            if ($args['type'] != "get" && $args['type'] != "post") {
                $this->api_fail = "API request type must be 'post' or 'get'.";
            } else {
                $return['type'] = $args['type'];
            }
        } else {
            $this->api_fail = "Invalid or missing API request type.";
        }

        // Define and check the URL
        if (isset($args['url']) && gettype($args['url']) == "string") {
            $return['url'] = $this->define_api_url(urldecode($args['url']));
        } else {
            $this->api_fail = "Invalid API url.";
        }

        // Define the method
        if (isset($args['method']) && $return['custom'] == false) {
            $return['method_class'] = "";
            if (gettype($args['method']) == "array") {
                count($args['method']) >= 1 ? $return['method_class'] = $args['method'][0] : $this->api_fail = "Undefined API method.";
                count($args['method']) >= 2 ? $return['method'] = $args['method'][1] : $this->api_fail = "Undefined API method after finding class.";
            } elseif (gettype($args['method'] == "string")) {
                $return['method'] = $args['method'];
            } else {
                $this->api_fail = "Invalid API method defined.";
            }
        } else {
            if ($return['custom'] == false) {
                $this->api_fail = "API method not defined.";
            }
        }

        // Define the data
        if (isset($args['data'])) {
            if (gettype($args['data']) == "array") {
                if ($this->array_is_associative($args['data']) == true) {
                    $return['data'] = $args['data'];
                } else {
                    $this->api_fail = "API data parameter must be a key => value array.";
                }
            } else {
                $this->api_fail = "API data parameter must be a key => value array.";
            }
        } else {
            $return['data'] = "";
        }

        // Define the API key
        if (isset($args['key'])) {
            if (gettype($args['key']) == "string") {
                $return['ajax-hash-data'] = urlencode(json_encode(array("key"=>$args['key'])));
            } else {
                $this->api_fail = "Invalid API key type.";
            }
        } else {
            $return['ajax-hash-data'] = urlencode(json_encode(array("key"=>$this->get_hash())));
        }

        // Remove anything that is normally pre-set but because it's a custom call
        if ($return['custom'] == true) {
            unset($return['api-key'], $return['ajax']);

            // Define the response type
            $return['response_type'] = false;
            if (isset($args['response_type'])) {
                // Check for allowed response types: JSON or XML
                if ($args['response_type'] == "json" || $args['response_type'] == "xml") {
                    $return['response_type'] = $args['response_type'];
                } else {
                    $this->api_fail = "The API response type must be either 'json' or 'xml'.";
                }
            }
        }

        return $return;
    }


    /**
     * Performs a check to see if cURL is an option on the server
     *
     * @return boolean
     */
    public function check_curl() {
        if (function_exists("curl_version")) return true;
        return false;
    }


    /**
     * Defines the variables that will be passed during the call
     *
     * @param array $args
     * @param boolean $get
     * @return array
     */
    private function define_api_variables($args, $get = false) {
        $return = array();
        $ignore = array("url", "type", "custom", "response_type");
        foreach ($args as $key => $value) {
            // If the key is meant to be ignored, ignore it
            if (in_array($key, $ignore)) continue;

            // If this is a Theamus -> Theamus ajax call
            if ($args['custom'] == false) {
                // If the value is an array, turn it into a JSON encoded string
                if (is_array($value)) {
                    $value = urlencode(json_encode($value));
                }

                // Add the key/value to the return array
                $return[] = $get == true ? urlencode("$key=$value") : "$key=$value";
            } else {
                // Loop through all of the data variables, defining them as a string
                foreach ($value as $k => $v) $return[] = "$k=$v";
            }
        }

        // If there are results to return, return them or nothing at all
        return count($return) >= 1 ? implode("&", $return) : "";
    }


    /**
     * Since an absolute path is required, check for the existance of a protocol and
     *  define the url based on the results from that
     *
     * @param string $url
     * @return string $new_url
     */
    private function define_api_url($url) {
        // Check if the url is expected to be an absolute path
        if (strpos($url, "http") !== false) {
            $new_url = $url;
        } else {
            // We will be assuming the host address or the predefined base url
            $new_url = base_url.$url;
        }

        // Check for url validation and return or throw error
        if (filter_var($new_url, FILTER_VALIDATE_URL)) {
            return $new_url;
        } else {
            // Define an error has happened and return blank
            $this->api_fail = "Invalid URL given.";
            return "";
        }
    }


    /**
     * Send the API out based on the arguments given
     *
     * @param array $args
     * @return string
     */
    private function send_api($args) {
        // Define options based on the call type
        if ($args['type'] == "post") {
            // Define the POST options
            $options = array(
                CURLOPT_POST                => 1,
                CURLOPT_HEADER              => 0,
                CURLOPT_URL                 => $args['url'],
                CURLOPT_FRESH_CONNECT       => 1,
                CURLOPT_RETURNTRANSFER      => 1,
                CURLOPT_FORBID_REUSE        => 1,
                CURLOPT_TIMEOUT             => 4,
                CURLOPT_POSTFIELDS          => $this->define_api_variables($args)
            );
        } elseif ($args['type'] == "get") {
            // Define the variables to send out
            $api_variables = $this->define_api_variables($args, true);

            // Define the separator from the url
            $var_starter = "";
            if ($args['custom'] == false && $api_variables != "") $var_starter = "&";
            if ($args['custom'] == true && $api_variables != "") $var_starter = "?";

            // Define the GET options
            $options = array(
                CURLOPT_URL                 => $args['url'].$var_starter.$api_variables,
                CURLOPT_HEADER              => 0,
                CURLOPT_RETURNTRANSFER      => 1,
                CURLOPT_TIMEOUT             => 4
            );
        }

        // Open the connection, set the options and execute
        $ch = curl_init();
        curl_setopt_array($ch, $options);
        $result = curl_exec($ch);

        // Find the status and throw an error, if applicable
        $ch_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        if ($ch_status != 200) {
            return $this->api_error("URL responded with an error.", $ch_status);
        } else {
            return $result;
        }
    }


    /**
     * Perfoms everything required to run an API call.
     *
     * @param array $args
     * @return array
     */
    public function api($args = array()) {
        $return = array();
        if (empty($args)) $return = $this->api_error("API arguments are required.");

        // Define and check the arguments
        $args = $this->api_check_args($args);

        // Make the call
        if ($this->check_curl() && $this->api_fail == false) {
            $return = $this->send_api($args);
        } else {
            $return = $this->api_error("You must have cURL available to make API requests.");
        }

        // Throw errors or return
        if ($this->api_fail != false) $return = $this->api_error($this->api_fail);

        if (!is_array($return)) {
            // Check the response type to return the proper data
            if (isset($args['response_type']) && $args['response_type'] == "xml") {
                return $this->xml_decode($return);
            } else {
                return json_decode($return, true);
            }
        } else {
            return $return;
        }
    }


    /**
     * Takes an array of data and defines it to be used within a SQL query
     *
     * @param array $data
     * @return array
     */
    private function define_query_data($data) {
        // Define the return array with a random number key/value
        $return = array("random_number" => rand(0, 999999999));

        // Loop through the given data to define the desired variables
        foreach ($data as $key => $value) {
            // If the value is an array recurse into it, defining it as a part of the return data
            if (is_array($value)) {
                $return['data'][] = $this->define_query_data($value);

            // If the value is not an array, define the desired return variables
            } else {
                // If MySQLi is being used
                if ($this->use_pdo == false) {
                    $return['columns'][] = "`$key`";
                    $return['prepare_keys'][] = "'".$this->connection->real_escape_string($value)."'";
                    $return['prepare_values'] = array();

                // If PDO is being used
                } else {
                    $random_key = ":".$key.$return['random_number'];            // random_key for shorter code
                    $return['columns'][]                    = "`$key`";
                    $return['prepare_keys'][]               = $random_key;
                    $return['prepare_values'][$random_key]  = $value;
                }
            }
        }

        // Return the desired data
        return $return;
    }


    /**
     * Takes an array of data and recursively turns it into a beautiful clause statement
     *
     * @param array $clause
     * @return string
     */
    private function define_clause($clause) {
        $return_clause = $return_inner = array(); // Defaults

        if (!isset($clause['conditions']) || !isset($clause['operator'])) {
            $this->clause_values = array();
            return "";
        }

        // Loop through all of the conditions
        foreach ($clause['conditions'] as $key => $value) {
            // If this condition is guessed to be another condition, recurse into it
            if (is_numeric($key)) {
                $return_clause[] = $this->define_clause($value);

            // If this is a condition value
            } else {
                // Define the key and the operator
                $first_character = substr($key, 0, 1);

                $equals = "=";
                $key = "`".$key."`";

                if ($first_character == "[") {
                    preg_match("/\[(.*?)\]/", $key, $matches);
                    for ($i = 0; $i < strlen($matches[1]); $i++) {
                        switch ($matches[1][$i]) {
                            case "!":
                                $equals = "!=";
                                $key = str_replace("!", "", $key);
                                break;
                            case "%":
                                $equals = "LIKE";
                                $key = str_replace("%", "", $key);
                                break;
                            case "`":
                                $key = str_replace("`", "", $key);
                                $equals = "=";
                                break;
                        }
                    }
                    $key = str_replace("[", "", str_replace("]", "", $key));
                }

                // If using MySQLi
                if ($this->use_pdo == false) {
                    // Define an escaped key/value combination and define the clause values as blank
                    $return_inner[] = "$key $equals '".$this->connection->real_escape_string($value)."'";
                    $this->clause_values = array();

                // If using PDO
                } else {
                    // Define a random key, then the key/value combination, then add the value to the clause values array
                    $random_key = ":".substr(md5($key.rand(0,999999999)), 0, 15);
                    $return_inner[] = "$key $equals $random_key";
                    $this->clause_values[$random_key] = $value;
                }
            }
        }

        // If returning values (children)
        if (!empty($return_inner)) {
            return "(".implode(" ".$clause['operator']." ", $return_inner).")";

        // If returning a complete child
        } else {
            return "(".implode(" ".$clause['operator']." ", $return_clause).")";
        }

        // Return the entire thing
        return $return_clause;
    }


    /**
     * Returns the amount of rows that exist in a database object
     *
     * @param object $object
     * @return int
     */
    public function count_rows($object) {
        if ($this->use_pdo == false) {
            return $object->num_rows;
        }
        return $object->rowCount();
    }


    /**
     * Gathers provided data and generates a SQL query to perform based on that data.
     *
     * @param string $table_name
     * @param array $data
     * @return boolean
     */
    public function insert_table_row($table_name = "", $data = array()) {
        if ($this->connection == false) {
            return false;
        }

        // Check the table_name and data variables for values
        if ($table_name == "" || empty($data)) {
            return false;
        }

        // Define the SQL statement information
        $sql = $this->define_query_data($data);

        // If a multi-query is going to happen
        if (isset($sql['data'])) {
            // Define the variables that will be used to create the SQL query
            $sql['prepare_values']  = array();
            $sql['statement']       = "";

            // Loop through the given data, creating one large multi-query
            foreach ($sql['data'] as $sql_data) {
                $sql_values[] = "(".implode(", ", $sql_data['prepare_keys']).")";
                $sql['prepare_values']   = array_merge($sql_data['prepare_values'], $sql['prepare_values']);
            }
            $sql['statement'] = "INSERT INTO `$table_name` (".implode(", ", $sql_data['columns']).") VALUES ".implode(", ", $sql_values).";";

            // Clean up the SQL data
            unset($sql['random_number'], $sql['data']);

        // If it's not a multi-query then define the statement
        } else {
            $sql['statement'] = "INSERT INTO `$table_name` (".implode(", ", $sql['columns']).") VALUES (".implode(", ", $sql['prepare_keys']).");";

            // Clean up the SQL data
            unset($sql['random_number'], $sql['columns'], $sql['prepare_keys']);
        }

        // Show the query if desired
        if ($this->show_query == true) {
            Pre(array("query" => $sql['statement'], "variables" => $sql['prepare_values']));
        }

        // If a connection exists
        if ($this->connection) {
            // If using MySQLi - run the query
            if ($this->use_pdo == false) {
                $query = $this->connection->query($sql['statement']);
                if ($query) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        Pre("The query failed to execute. Code: ".$this->connection->errno." - Message: ".$this->connection->error);
                    }
                    return false;
                }

            // If using PDO - prepare the statement and execute
            } else {
                $query = $this->connection->prepare($sql['statement']);
                if ($query->execute($sql['prepare_values'])) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        $query_error = $query->errorInfo();
                        Pre("The query failed to execute. Code: ".$query_error[1]." - Message: ".$query_error[2]);
                    }
                    return false;
                }
            }
        }
        return false;
    }


    /**
     * Updates a table row based on the information given
     *
     * @param string $table_name
     * @param array $data
     * @param array $clause
     * @return boolean
     */
    public function update_table_row($table_name = "", $data = array(), $clause = array()) {
        if ($this->connection == false) {
            return false;
        }

        // Check the table_name and data variables for values
        if ($table_name == "" || empty($data)) {
            return false;
        }

        // Define the query data
        $sql = $this->define_query_data($data);

        $sql    = isset($sql['data']) ? $sql : array("data" => array($sql));
        $clause = isset($clause[0]) ? $clause : array($clause);
        if (isset($sql['data'])) {

            if (count($sql['data']) != count($clause)) {
                return false;
            }

            for ($s = 0; $s < count($sql['data']); $s++) {
                $data = $sql['data'][$s];
                $temp_clause = isset($clause[$s]) ? $clause[$s] : array();

                // Let the parameters start fresh
                $this->clause_values = array();
                $set = array();

                // If using MySQLi
                if ($this->use_pdo == false) {
                    // Loop through the values, defining them to be used in the statement
                    for ($i = 0; $i < count($data['columns']); $i++) {
                        $set[] = $data['columns'][$i]." = ".$data['prepare_keys'][$i];
                    }

                // If using PDO
                } else {
                    // Loop through the values, defining them to be used in the statement
                    foreach (array_keys($data['prepare_values']) as $key) {
                        $set[] = "`".trim(trim($key, ":"), $data['random_number'])."` = ".$key;
                    }
                }

                // If there is a WHERE
                if (!empty($temp_clause)) {
                    // Define the WHERE statement values, merge the clause values with the set items values then define the statment
                    $where = $this->define_clause($temp_clause);
                    $temp_clause = $where != "" ? " WHERE $where" : "";
                    $temp_prepare_values[] = array_merge($this->clause_values, $data['prepare_values']);
                    $temp_queries[] = "UPDATE `$table_name` SET ".implode(", ", $set).$temp_clause.";";

                // No WHERE - define a statement for all!
                } else {
                    $temp_prepare_values[] = $data['prepare_values'];
                    $temp_queries[] = "UPDATE `$table_name` SET ".implode(", ", $set).";";
                }
            }

            // Flatten the prepared values
            $sql['prepare_values'] = array();
            foreach ($temp_prepare_values as $prepare_value) {
                $sql['prepare_values'] = array_merge($prepare_value, $sql['prepare_values']);
            }

            // Flatten the queries
            $sql['statement'] = implode(" ", $temp_queries);
        }

        // Show the query if desired
        if ($this->show_query == true) {
            Pre(array("query" => $sql['statement'], "variables" => $sql['prepare_values']));
        }


        // If a connection exists
        if ($this->connection) {
            // If using MySQLi - run the query
            if ($this->use_pdo == false) {
                $return = $this->connection->multi_query($sql['statement']) ? true : false;
                if ($return) {
                    while ($this->connection->next_result()) continue;
                    return $return;
                } else {
                    if ($this->show_query_errors == true) {
                        Pre("The query failed to execute. Code: ".$this->connection->errno." - Message: ".$this->connection->error);
                    }
                    return false;
                }

            // If using PDO - prepare the statement and execute
            } else {
                $query = $this->connection->prepare($sql['statement']);
                if ($query->execute($sql['prepare_values'])) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        $query_error = $query->errorInfo();
                        Pre("The query failed to execute. Code: ".$query_error[1]." - Message: ".$query_error[2]);
                    }
                    return false;
                }
            }
        }
        return false;
    }


    /**
     * Deletes a row from a database table
     *
     * @param string $table_name
     * @param string $clause
     * @return boolean
     */
    public function delete_table_row($table_name = "", $clause = array()) {
        if ($this->connection == false) {
            return false;
        }

        // Let the parameters start fresh
        $this->clause_values = array();

        // Check the table_name and data variables for values
        if ($table_name == "") {
            return false;
        }

        $temp_statement = $temp_values = array();

        // If there is a WHERE
        if (!empty($clause)) {
            $clauses = isset($clause[0]) ? $clause : array($clause);
            foreach ($clauses as $clause) {
                // Define the WHERE statement values, define the prepare values and the statement
                $where = $this->define_clause($clause);
                $clause = $where != "" ? " WHERE $where" : "";

                $temp_statement[] = "DELETE FROM `$table_name`$clause;";
                $temp_prepare_values[] = $this->clause_values;
            }
        // No WHERE - define a statement for all
        } else {
            $temp_statement[] = "DELETE FROM `$table_name`;";
            $temp_prepare_values[] = array();
        }

        // Flatten the prepared values
        $sql['prepare_values'] = array();
        foreach ($temp_prepare_values as $prepare_value) {
            $sql['prepare_values'] = array_merge($prepare_value, $sql['prepare_values']);
        }

        $sql['statement'] = implode(" ", $temp_statement);

        // Show the query if desired
        if ($this->show_query == true) {
            Pre(array("query" => $sql['statement'], "variables" => $sql['prepare_values']));
        }

        // If a connection exists
        if ($this->connection) {
            // If using MySQLi - run the query
            if ($this->use_pdo == false) {
                $query = $this->connection->query($sql['statement']);
                if ($query) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        Pre("The query failed to execute. Code: ".$this->connection->errno." - Message: ".$this->connection->error);
                    }
                    return false;
                }

            // If using PDO - prepare the statement and execute
            } else {
                $query = $this->connection->prepare($sql['statement']);
                if ($query->execute($sql['prepare_values'])) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        $query_error = $query->errorInfo();
                        Pre("The query failed to execute. Code: ".$query_error[1]." - Message: ".$query_error[2]);
                    }
                    return false;
                }
            }
        }
        return false;
    }


    /**
     * Selects rows from a table and returns the object holding them, or returns false if there is an error
     *
     * @param string $table_name
     * @param array $columns
     * @param array $clause
     * @return boolean|object
     */
    public function select_from_table($table_name = "", $columns = array(), $clause = array(), $extras = "") {
        if ($this->connection == false) {
            if ($this->show_query_errors == true) {
                Pre("Cannot perform query because there is no connection available.");
            }
            return false;
        }

        // Let the parameters start fresh
        $this->clause_values = array();

        // Check the table_name and data variables for values
        if ($table_name == "") {
            if ($this->show_query_errors == true) {
                Pre("Query was unsuccessful because there was no table name defined.");
            }
            return false;
        }

        // Define the columns
        if (empty($columns)) {
            $columns = "*";
        } else {
            foreach ($columns as $column) {
                $prepared_columns[] = "`$column`";
            }
            $columns = implode(", ", $prepared_columns);
        }

        // Define the extras
        if ($extras != "") {
            $extras = " $extras";
        }

        // If there is a WHERE
        if (!empty($clause)) {
            // Define the WHERE statement values, define the prepare values and the statement
            $where = $this->define_clause($clause);
            $clause = $where != "" ? " WHERE $where" : "";

            $sql['statement'] = "SELECT $columns FROM `$table_name`$clause"."$extras;";
            $sql['prepare_values'] = $this->clause_values;

        // No WHERE - define a statement for all
        } else {
            $sql['statement'] = "SELECT $columns FROM `$table_name`"."$extras;";
            $sql['prepare_values'] = array();
        }

        // Show the query if desired
        if ($this->show_query == true) {
            Pre(array("query" => $sql['statement'], "variables" => $sql['prepare_values']));
        }

        // If a connection exists
        if ($this->connection) {
            // If using MySQLi - run the query
            if ($this->use_pdo == false) {
                $query = $this->connection->query($sql['statement']);
                if ($query) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        Pre("The query failed to execute. Code: ".$this->connection->errno." - Message: ".$this->connection->error);
                    }
                    return false;
                }

            // If using PDO - prepare the statement and execute
            } else {
                $query = $this->connection->prepare($sql['statement']);
                if ($query->execute($sql['prepare_values'])) {
                    return $query;
                } else {
                    if ($this->show_query_errors == true) {
                        $query_error = $query->errorInfo();
                        Pre("The query failed to execute. Code: ".$query_error[1]." - Message: ".$query_error[2]);
                    }
                    return false;
                }
            }
        }
        if ($this->show_query_errors == true) {
            Pre("Nothing worked for this query.  The function ran but nothing happened.");
        }
        return false;
    }


    /**
     * Fetches rows from a SQL query object and returns them as an array of data
     *
     * @param object $object
     * @param string $mysqli_fetch
     * @param long $pdo_fetch
     * @return array
     */
    public function fetch_rows($object, $mysqli_fetch = "fetch_assoc", $pdo_fetch = PDO::FETCH_ASSOC) {
        // If using MySQLi
        if ($this->use_pdo == false) {
            // If there are multiple rows to return
            if ($object->num_rows > 0) {
                // Loop through all of the rows, adding them to a return catch
                while ($row = $object->$mysqli_fetch()) {
                    $return[] = $row;
                }

                // Return the data as it should be depending on the amount of results
                return count($return) > 1 ? $return : $return[0];
            }

            // Return the whole thing as is
            return $object->$mysqli_fetch();
        } else {
            // If there are multiple rows to return
            if ($object->rowCount() > 1) {
                // Return the whole thing as is
                return $object->fetchAll($pdo_fetch);
            } else {
                // Define all of the information into an array
                $row = $object->fetchAll($pdo_fetch);

                // Return the data as it should be depending on the amount of results
                return isset($row[0]) ? $row[0] : $row;
            }
        }
    }


    /**
     * Takes a given string (query statement) and runs it with sanitized, safe variables
     *
     * @param string $query
     * @param array $variables
     * @return boolean
     */
    public function custom_query($query, $variables = array()) {
        // Show the query if desired
        if ($this->show_query == true) {
            Pre(array("query" => $query, "variables" => $variables));
        }

        // If a connection exists
        if ($this->connection) {
            // If using MySQLi - run the query
            if ($this->use_pdo == false) {
                foreach($variables as $key => $variable) {
                    $query = str_replace($key, "'".$this->connection->real_escape_string($variable)."'", $query);
                }
                return $this->connection->query($query);

            // If using PDO - prepare the statement and execute
            } else {
                $query = $this->connection->prepare($query);
                if ($query->execute($variables)) {
                    return $query;
                }
                return false;
            }
        }
        return false;
    }
}
